FROM ruby:3.2.2-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev libvips pkg-config curl

# We'll install gems in the volume during boot
ENV BUNDLE_PATH /usr/local/bundle
