/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ConectarRouteImport } from './routes/conectar'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DadosColetadosRouteImport } from './routes/dados-coletados'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FluxosRouteImport } from './routes/fluxos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConectarRoute = ConectarRouteImport.update({
  id: '/conectar',
  path: '/conectar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosColetadosRoute = DadosColetadosRouteImport.update({
  id: '/dados-coletados',
  path: '/dados-coletados',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxosRoute = FluxosRouteImport.update({
  id: '/fluxos',
  path: '/fluxos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/automacoes': typeof AutomacoesRoute
  '/cadastro': typeof CadastroRoute
  '/conectar': typeof ConectarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dados-coletados': typeof DadosColetadosRoute
  '/entrar': typeof EntrarRoute
  '/fluxos': typeof FluxosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/automacoes': typeof AutomacoesRoute
  '/cadastro': typeof CadastroRoute
  '/conectar': typeof ConectarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dados-coletados': typeof DadosColetadosRoute
  '/entrar': typeof EntrarRoute
  '/fluxos': typeof FluxosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/automacoes': typeof AutomacoesRoute
  '/cadastro': typeof CadastroRoute
  '/conectar': typeof ConectarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dados-coletados': typeof DadosColetadosRoute
  '/entrar': typeof EntrarRoute
  '/fluxos': typeof FluxosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamento'
    | '/automacoes'
    | '/cadastro'
    | '/conectar'
    | '/configuracoes'
    | '/dados-coletados'
    | '/entrar'
    | '/fluxos'
    | '/privacidade'
    | '/termos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamento'
    | '/automacoes'
    | '/cadastro'
    | '/conectar'
    | '/configuracoes'
    | '/dados-coletados'
    | '/entrar'
    | '/fluxos'
    | '/privacidade'
    | '/termos'
  id:
    | '__root__'
    | '/'
    | '/agendamento'
    | '/automacoes'
    | '/cadastro'
    | '/conectar'
    | '/configuracoes'
    | '/dados-coletados'
    | '/entrar'
    | '/fluxos'
    | '/privacidade'
    | '/termos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentoRoute: typeof AgendamentoRoute
  AutomacoesRoute: typeof AutomacoesRoute
  CadastroRoute: typeof CadastroRoute
  ConectarRoute: typeof ConectarRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DadosColetadosRoute: typeof DadosColetadosRoute
  EntrarRoute: typeof EntrarRoute
  FluxosRoute: typeof FluxosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conectar': {
      id: '/conectar'
      path: '/conectar'
      fullPath: '/conectar'
      preLoaderRoute: typeof ConectarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados-coletados': {
      id: '/dados-coletados'
      path: '/dados-coletados'
      fullPath: '/dados-coletados'
      preLoaderRoute: typeof DadosColetadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxos': {
      id: '/fluxos'
      path: '/fluxos'
      fullPath: '/fluxos'
      preLoaderRoute: typeof FluxosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentoRoute: AgendamentoRoute,
  AutomacoesRoute: AutomacoesRoute,
  CadastroRoute: CadastroRoute,
  ConectarRoute: ConectarRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DadosColetadosRoute: DadosColetadosRoute,
  EntrarRoute: EntrarRoute,
  FluxosRoute: FluxosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
